lrvl:
    just render_local manim_very_low.cfg 360p15

lrl:
    just render_local manim_low.cfg 720p30

lrf:
    just render_local manim.cfg 2160p60

render_local config quality:
    manim \
        --format mp4 \
        -c cfg/{{config}} \
        --disable_caching \
        -p \
        main.py